spring:
  application:
      name: cruddemo
  datasource:
      url: jdbc:mysql://localhost:3306/blog_directory
      username: springstudent
      password: springstudent

jwt:
  secret: bVYp7uF83m6Zs8jF4kLd9xP0rTn2qWe5yHcXzBvN8mRq3sGfD1aJkLpOeRtYwUi

#  security:
#      user:
#        name: user
#        password: user

#springdoc.swagger-ui.path=/my-ui.html
#springdoc.api-docs.path=/api-ui