spring:
  application:
      name: cruddemo
  datasource:
      url: ${DB_URL:jdbc:mysql://localhost:3306/blog_directory}
      username: ${DB_USERNAME:ouda}
      password: ${DB_PASSWORD:password}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.cache.interceptor: TRACE
    org.springframework.cache.support: TRACE
jwt:
  secret: ${JWT_SECRET:bVYp7uF83m6Zs8jF4kLd9xP0rTn2qWe5yHcXzBvN8mRq3sGfD1aJkLpOeRtYwUi}

#  security:
#      user:
#        name: user
#        password: user

#springdoc.swagger-ui.path=/my-ui.html
#springdoc.api-docs.path=/api-ui